version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - ./my-datavolume:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: nourhenechalghoumi/devops_project
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devops?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: on-failure

  frontend:
    image: nourhenechalghoumi/devops_project_front
    ports:
      - "80:80"
    depends_on:
      - backend

  SonarQ:
    image: sonarqube:8.9.7-community
  
  Nex:
    image: sonatype/nexus3
